version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - goconst
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gosec:
      excludes:
        - G404
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - .*_test\.go$
      - vendor/
      - test/
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - vendor/
      - test/
      - third_party$
      - builtin$
      - examples$
